.PHONY: clean All

All:
	@echo "----------Building project:[ Mystring-operators - Debug ]----------"
	@cd "Mystring-operators" && "$(MAKE)" -f  "Mystring-operators.mk"
clean:
	@echo "----------Cleaning project:[ Mystring-operators - Debug ]----------"
	@cd "Mystring-operators" && "$(MAKE)" -f  "Mystring-operators.mk" clean
