.PHONY: clean All

All:
	@echo "----------Building project:[ Loops_Code_Snip - Debug ]----------"
	@cd "Loops_Code_Snip" && "$(MAKE)" -f  "Loops_Code_Snip.mk"
clean:
	@echo "----------Cleaning project:[ Loops_Code_Snip - Debug ]----------"
	@cd "Loops_Code_Snip" && "$(MAKE)" -f  "Loops_Code_Snip.mk" clean
