.PHONY: clean All

All:
	@echo "----------Building project:[ CatchCPPExceptions - Debug ]----------"
	@cd "CatchCPPExceptions" && "$(MAKE)" -f  "CatchCPPExceptions.mk"
clean:
	@echo "----------Cleaning project:[ CatchCPPExceptions - Debug ]----------"
	@cd "CatchCPPExceptions" && "$(MAKE)" -f  "CatchCPPExceptions.mk" clean
