.PHONY: clean All

All:
	@echo "----------Building project:[ Letter_Pyramid_Final - Debug ]----------"
	@cd "Letter_Pyramid_Final" && "$(MAKE)" -f  "Letter_Pyramid_Final.mk"
clean:
	@echo "----------Cleaning project:[ Letter_Pyramid_Final - Debug ]----------"
	@cd "Letter_Pyramid_Final" && "$(MAKE)" -f  "Letter_Pyramid_Final.mk" clean
